### ISSUE TITLE
Problems making with downloaded src

### ISSUE THREAD

**Issue by ruddj** [sdsc/mlnx-ofed-roll#1] opened 2016-04-12 00:07 UTC
Good Day,
 When I try to make the roll it fails at verifying file size and hashes.

Steps to reproduce on a server without access to SDSC files

```
git clone https://github.com/sdsc/mlnx-ofed-roll.git
cd mlnx-ofed-roll/
make default 2>&1 | tee build-1.log
# Fails downloading http://forge.sdsc.edu/triton/mlnx-ofed/src/mlnx-ofed-linux/MLNX_OFED_LINUX-3.1-1.0.3-rhel6.7-x86_64.tgz
cd src/mlnx-ofed-linux/
wget http://www.mellanox.com/downloads/ofed/MLNX_OFED-3.1-1.1.2.0/MLNX_OFED_LINUX-3.1-1.1.2.0-rhel6.7-x86_64.tgz
vi version.mk
=========
VERSION           = 3.1
RELEASE           = 1.1.2.0
EXTRA             = rhel6.7-x86_64
==========
cd ../..
make default 2>&1 | tee build-2.log
```

Fails at 

```
make[4]: Entering directory `/export/rocks/update/mlnx-ofed-roll/BUILD/mlnx-ofed-linux-3.1'
::: Downloading http://forge.sdsc.edu/triton/mlnx-ofed/src/mlnx-ofed-linux/MLNX_OFED_LINUX-3.1-1.1.2.0-rhel6.7-x86_64.tgz :::
::: MLNX_OFED_LINUX-3.1-1.1.2.0-rhel6.7-x86_64.tgz already exists, skipping :::
::: Verifying size of MLNX_OFED_LINUX-3.1-1.1.2.0-rhel6.7-x86_64.tgz :::
make[4]: *** [MLNX_OFED_LINUX-3.1-1.1.2.0-rhel6.7-x86_64.tgz] Error 1
```

If i then comment out lines verify size and verify hash it makes correctly

```
diff --git a/src/mlnx-ofed-linux/pull.mk b/src/mlnx-ofed-linux/pull.mk
index 45dac4c..e533146 100644
--- a/src/mlnx-ofed-linux/pull.mk
+++ b/src/mlnx-ofed-linux/pull.mk
@@ -31,9 +31,9 @@ $(SRC_PKGS):
          fi
        @echo "::: Verifying size of $@ :::"
        @#$(GREP.CMD) `$(STAT.CMD) -s $@ | cut -d' ' -f8 | cut -d'=' -f2` $(VERIFY.HASHES) # MacOS
-       @$(GREP.CMD) `$(STAT.CMD) --printf="%s" $@` $(VERIFY.HASHES) # Linux
+       @#$(GREP.CMD) `$(STAT.CMD) --printf="%s" $@` $(VERIFY.HASHES) # Linux
        @echo "::: Verifying hash of $@ :::"
-       @$(GREP.CMD) `$(VERIFY.CMD) $(VERIFY.OPTS) $@ ` $(VERIFY.HASHES)
+       @#$(GREP.CMD) `$(VERIFY.CMD) $(VERIFY.OPTS) $@ ` $(VERIFY.HASHES)
        @echo ""
```

[build-1.log.txt](https://github.com/sdsc/mlnx-ofed-roll/files/214103/build-1.log.txt)
[build-2.log.txt](https://github.com/sdsc/mlnx-ofed-roll/files/214104/build-2.log.txt)

Thank you,
 James

**Comment by tcooper** [comment] 2016-04-12 00:33
This is by design.

If you want/need to build with a different version of MLNX_OFED_LINUX than is referenced in the source and downloadable from our server you need to...
- edit the version.mk file (which you've done)
- provide the archive/ISO that you wish to use (which you've done) OR provide an alternate DL.SERVER and DL.PATH in Pull.mk
- and add the sha1sum for the archive/ISO to binary_hashes (which you need to do).

A script to generate the required hash can be found [here](https://github.com/sdsc/skeleton-roll/blob/master/gen_hash.sh)

After updating binary_hashes you should be able to build the roll without problems.

**Comment by ruddj** [comment] 2016-04-12 00:42
Thanks Trevor. Would it be possible to add instructions to the README.md file to that affect? 
I was using an existing post to Rocks Discussion list about using updated sources as a source of info
https://lists.sdsc.edu/pipermail/npaci-rocks-discussion/2015-November/068239.html

> If you decide to download a different MLNX_OFED_LINUX tarball you will also need to edit the src/mlnx-ofed-linux/version.mk file appropriately.

Having a sub-heading of README file that details how to use for users without SDSC source access would be very useful.

Thanks for your help, James

**Comment by tcooper** [comment] 2016-04-12 19:41
Adding the requested information is reasonable. We'll close this issue when the README has been updated.

**Comment by tcooper** [comment] 2017-02-13 17:25
Resolved in https://github.com/sdsc/mlnx-ofed-roll/commit/1334f2e90c3d462b7a7f688380dac9c8bd1c3258

**Closed as completed by tcooper** 2017-02-13 17:25 UTC
Labels: help wanted
